package com.chacha20;

import java.util.Arrays;

/**
 * Implementation of the IETF ChaCha20 Stream Cipher as specified in RFC 8439.
 *
 * <p>ChaCha20 is a high-speed, secure symmetric stream cipher designed by Daniel J. Bernstein.
 * It operates on 512-bit (64-byte) blocks with:
 * <ul>
 *   <li>256-bit key (32 bytes)</li>
 *   <li>96-bit nonce (12 bytes)</li>
 *   <li>32-bit block counter (4 bytes)</li>
 *   <li>512-bit internal state arranged as a 4x4 matrix of 32-bit words</li>
 *   <li>20 rounds (10 double rounds of 4 column rounds and 4 diagonal rounds)</li>
 *   <li>Quarter round operations using Addition modulo 2^32, XOR, and left rotations</li>
 * </ul>
 *
 * <p>The cipher keystream is generated by serializing the output state and XORing it with the input data.
 * Because XOR is self-inverting, encryption and decryption use the identical keystream generation process.
 */
public class ChaCha20 {

    // RFC 8439 Section 2.1: Constants representing ASCII string "expand 32-byte k" in little-endian order
    // "expa" -> 0x61707865
    public static final int CONSTANT_0 = 0x61707865;
    // "nd 3" -> 0x3320646e
    public static final int CONSTANT_1 = 0x3320646e;
    // "2-by" -> 0x79622d32
    public static final int CONSTANT_2 = 0x79622d32;
    // "te k" -> 0x6b206574
    public static final int CONSTANT_3 = 0x6b206574;

    public static final int STATE_SIZE_WORDS = 16;
    public static final int BLOCK_SIZE_BYTES = 64;
    public static final int NUM_ROUNDS = 20;

    /**
     * Performs a 32-bit left rotation.
     *
     * @param value the 32-bit integer value
     * @param distance rotation distance in bits
     * @return rotated 32-bit integer
     */
    public static int rotateLeft(int value, int distance) {
        return Integer.rotateLeft(value, distance);
    }

    /**
     * ChaCha20 Quarter Round operation (RFC 8439 Section 2.1).
     * Modifies four 32-bit words in place within the state array.
     *
     * <p>Formulas:
     * <pre>
     * a += b; d ^= a; d <<<= 16;
     * c += d; b ^= c; b <<<= 12;
     * a += b; d ^= a; d <<<= 8;
     * c += d; b ^= c; b <<<= 7;
     * </pre>
     *
     * @param state the 16-word state array
     * @param a index of word a
     * @param b index of word b
     * @param c index of word c
     * @param d index of word d
     */
    public static void quarterRound(int[] state, int a, int b, int c, int d) {
        state[a] += state[b];
        state[d] ^= state[a];
        state[d] = Integer.rotateLeft(state[d], 16);

        state[c] += state[d];
        state[b] ^= state[c];
        state[b] = Integer.rotateLeft(state[b], 12);

        state[a] += state[b];
        state[d] ^= state[a];
        state[d] = Integer.rotateLeft(state[d], 8);

        state[c] += state[d];
        state[b] ^= state[c];
        state[b] = Integer.rotateLeft(state[b], 7);
    }

    /**
     * Quarter round on 4 standalone 32-bit words (useful for test vectors).
     *
     * @param a input word a
     * @param b input word b
     * @param c input word c
     * @param d input word d
     * @return 4-element int array [a, b, c, d] after quarter round transformation
     */
    public static int[] quarterRound(int a, int b, int c, int d) {
        int[] state = new int[]{a, b, c, d};
        quarterRound(state, 0, 1, 2, 3);
        return state;
    }

    /**
     * Converts 4 consecutive bytes from a byte array into a 32-bit unsigned word
     * in little-endian byte ordering (RFC 8439 Section 2.1).
     *
     * @param bytes the source byte array
     * @param offset the starting index in the byte array
     * @return the 32-bit integer word
     */
    public static int bytesToWordLittleEndian(byte[] bytes, int offset) {
        return (bytes[offset] & 0xFF)
                | ((bytes[offset + 1] & 0xFF) << 8)
                | ((bytes[offset + 2] & 0xFF) << 16)
                | ((bytes[offset + 3] & 0xFF) << 24);
    }

    /**
     * Converts a 32-bit word into 4 consecutive bytes in little-endian byte ordering.
     *
     * @param word the 32-bit integer word
     * @param out the destination byte array
     * @param offset the starting index in the destination byte array
     */
    public static void wordToBytesLittleEndian(int word, byte[] out, int offset) {
        out[offset] = (byte) (word & 0xFF);
        out[offset + 1] = (byte) ((word >>> 8) & 0xFF);
        out[offset + 2] = (byte) ((word >>> 16) & 0xFF);
        out[offset + 3] = (byte) ((word >>> 24) & 0xFF);
    }

    /**
     * Constructs the initial 16-word (512-bit) ChaCha20 state according to RFC 8439.
     *
     * <p>State Layout (4x4 matrix of 32-bit words):
     * <pre>
     *  c0   c1   c2   c3
     *  k0   k1   k2   k3
     *  k4   k5   k6   k7
     *  ctr  n0   n1   n2
     * </pre>
     *
     * @param key 256-bit key (32 bytes)
     * @param counter 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @return 16-word integer array representing initial state
     */
    public static int[] createInitialState(byte[] key, int counter, byte[] nonce) {
        InputValidator.validateKey(key);
        InputValidator.validateNonce(nonce);

        int[] state = new int[STATE_SIZE_WORDS];

        // Constants (words 0..3)
        state[0] = CONSTANT_0;
        state[1] = CONSTANT_1;
        state[2] = CONSTANT_2;
        state[3] = CONSTANT_3;

        // Key (words 4..11) - 8 words (32 bytes)
        for (int i = 0; i < 8; i++) {
            state[4 + i] = bytesToWordLittleEndian(key, i * 4);
        }

        // Block Counter (word 12)
        state[12] = counter;

        // Nonce (words 13..15) - 3 words (12 bytes)
        for (int i = 0; i < 3; i++) {
            state[13 + i] = bytesToWordLittleEndian(nonce, i * 4);
        }

        return state;
    }

    /**
     * Executes a specified number of rounds of the ChaCha permutation on the state.
     * Rounds must be an even integer (e.g. 8 for ChaCha8, 12 for ChaCha12, 20 for ChaCha20).
     *
     * @param state the 16-word state array to permute in place
     * @param rounds total number of rounds (e.g., 8, 12, 20)
     */
    public static void applyRounds(int[] state, int rounds) {
        if (rounds <= 0 || rounds % 2 != 0) {
            throw new IllegalArgumentException("Rounds must be a positive even integer (e.g., 8, 12, 20).");
        }
        int doubleRounds = rounds / 2;
        for (int i = 0; i < doubleRounds; i++) {
            // Column Round (4 quarter rounds)
            quarterRound(state, 0, 4, 8, 12);
            quarterRound(state, 1, 5, 9, 13);
            quarterRound(state, 2, 6, 10, 14);
            quarterRound(state, 3, 7, 11, 15);

            // Diagonal Round (4 quarter rounds)
            quarterRound(state, 0, 5, 10, 15);
            quarterRound(state, 1, 6, 11, 12);
            quarterRound(state, 2, 7, 8, 13);
            quarterRound(state, 3, 4, 9, 14);
        }
    }

    /**
     * Executes the standard 20 rounds of the ChaCha20 permutation on the state (RFC 8439 Section 2.3).
     * Consists of 10 double rounds (each containing 4 column rounds and 4 diagonal rounds).
     *
     * @param state the 16-word state array to permute in place
     */
    public static void applyRounds(int[] state) {
        applyRounds(state, NUM_ROUNDS);
    }

    /**
     * Applies a single round (either column or diagonal) to the working state.
     * Round index is 1-based (odd = column round, even = diagonal round).
     *
     * @param state 16-word state array
     * @param roundNumber 1-based round index (1..20)
     */
    public static void applySingleRound(int[] state, int roundNumber) {
        if (roundNumber % 2 == 1) {
            // Column Round
            quarterRound(state, 0, 4, 8, 12);
            quarterRound(state, 1, 5, 9, 13);
            quarterRound(state, 2, 6, 10, 14);
            quarterRound(state, 3, 7, 11, 15);
        } else {
            // Diagonal Round
            quarterRound(state, 0, 5, 10, 15);
            quarterRound(state, 1, 6, 11, 12);
            quarterRound(state, 2, 7, 8, 13);
            quarterRound(state, 3, 4, 9, 14);
        }
    }

    /**
     * Computes the ChaCha block function with configurable rounds.
     * Generates a 64-byte keystream block from key, counter, and nonce.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @param rounds number of rounds (e.g., 8, 12, 20)
     * @return 64-byte keystream block
     */
    public static byte[] chachaBlock(byte[] key, int counter, byte[] nonce, int rounds) {
        int[] initialState = createInitialState(key, counter, nonce);
        return chachaBlockFromState(initialState, rounds);
    }

    /**
     * Computes the standard ChaCha20 block function (RFC 8439 Section 2.3).
     * Generates a 64-byte keystream block from key, counter, and nonce.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @return 64-byte keystream block
     */
    public static byte[] chachaBlock(byte[] key, int counter, byte[] nonce) {
        return chachaBlock(key, counter, nonce, NUM_ROUNDS);
    }

    /**
     * Computes the 64-byte keystream block from an initialized 16-word state with configurable rounds.
     *
     * @param initialState 16-word initial state
     * @param rounds number of rounds (e.g. 8, 12, 20)
     * @return 64-byte keystream block
     */
    public static byte[] chachaBlockFromState(int[] initialState, int rounds) {
        if (initialState == null || initialState.length != STATE_SIZE_WORDS) {
            throw new IllegalArgumentException("Initial state must contain exactly 16 words.");
        }

        // Copy initial state to working state
        int[] workingState = Arrays.copyOf(initialState, STATE_SIZE_WORDS);

        // Apply rounds
        applyRounds(workingState, rounds);

        // Add the original state back to the working state (addition modulo 2^32)
        int[] outputState = new int[STATE_SIZE_WORDS];
        for (int i = 0; i < STATE_SIZE_WORDS; i++) {
            outputState[i] = workingState[i] + initialState[i];
        }

        // Serialize the 16 words into a 64-byte keystream block in little-endian order
        byte[] keystream = new byte[BLOCK_SIZE_BYTES];
        for (int i = 0; i < STATE_SIZE_WORDS; i++) {
            wordToBytesLittleEndian(outputState[i], keystream, i * 4);
        }

        return keystream;
    }

    /**
     * Computes the 64-byte keystream block from an initialized 16-word state using 20 rounds.
     *
     * @param initialState 16-word initial state
     * @return 64-byte keystream block
     */
    public static byte[] chachaBlockFromState(int[] initialState) {
        return chachaBlockFromState(initialState, NUM_ROUNDS);
    }

    /**
     * Encrypts the plaintext using ChaCha stream cipher with specified key, counter, nonce, and round count.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter initial 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @param plaintext plaintext byte array of arbitrary length
     * @param rounds number of permutation rounds (e.g., 8, 12, 20)
     * @return ciphertext byte array
     */
    public static byte[] encrypt(byte[] key, int counter, byte[] nonce, byte[] plaintext, int rounds) {
        InputValidator.validateKey(key);
        InputValidator.validateNonce(nonce);
        InputValidator.validateData(plaintext);

        if (plaintext.length == 0) {
            return new byte[0];
        }

        byte[] ciphertext = new byte[plaintext.length];
        int numBlocks = (plaintext.length + BLOCK_SIZE_BYTES - 1) / BLOCK_SIZE_BYTES;

        for (int blockIndex = 0; blockIndex < numBlocks; blockIndex++) {
            int currentCounter = counter + blockIndex;
            byte[] keystreamBlock = chachaBlock(key, currentCounter, nonce, rounds);

            int offset = blockIndex * BLOCK_SIZE_BYTES;
            int bytesToProcess = Math.min(BLOCK_SIZE_BYTES, plaintext.length - offset);

            for (int i = 0; i < bytesToProcess; i++) {
                ciphertext[offset + i] = (byte) (plaintext[offset + i] ^ keystreamBlock[i]);
            }
        }

        return ciphertext;
    }

    /**
     * Encrypts the plaintext using standard 20-round ChaCha20 stream cipher.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter initial 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @param plaintext plaintext byte array
     * @return ciphertext byte array
     */
    public static byte[] encrypt(byte[] key, int counter, byte[] nonce, byte[] plaintext) {
        return encrypt(key, counter, nonce, plaintext, NUM_ROUNDS);
    }

    /**
     * Overloaded encryption method with default initial counter = 1.
     *
     * @param key 256-bit key (32 bytes)
     * @param nonce 96-bit nonce (12 bytes)
     * @param plaintext plaintext byte array
     * @return ciphertext byte array
     */
    public static byte[] encrypt(byte[] key, byte[] nonce, byte[] plaintext) {
        return encrypt(key, 1, nonce, plaintext, NUM_ROUNDS);
    }

    /**
     * Decrypts the ciphertext using ChaCha stream cipher with specified rounds.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter initial 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @param ciphertext ciphertext byte array
     * @param rounds number of rounds (e.g., 8, 12, 20)
     * @return decrypted plaintext byte array
     */
    public static byte[] decrypt(byte[] key, int counter, byte[] nonce, byte[] ciphertext, int rounds) {
        return encrypt(key, counter, nonce, ciphertext, rounds);
    }

    /**
     * Decrypts the ciphertext using ChaCha20 stream cipher with specified key, counter, and nonce.
     *
     * @param key 256-bit key (32 bytes)
     * @param counter initial 32-bit block counter
     * @param nonce 96-bit nonce (12 bytes)
     * @param ciphertext ciphertext byte array
     * @return decrypted plaintext byte array
     */
    public static byte[] decrypt(byte[] key, int counter, byte[] nonce, byte[] ciphertext) {
        return encrypt(key, counter, nonce, ciphertext, NUM_ROUNDS);
    }

    /**
     * Overloaded decryption method with default initial counter = 1.
     *
     * @param key 256-bit key (32 bytes)
     * @param nonce 96-bit nonce (12 bytes)
     * @param ciphertext ciphertext byte array
     * @return decrypted plaintext byte array
     */
    public static byte[] decrypt(byte[] key, byte[] nonce, byte[] ciphertext) {
        return decrypt(key, 1, nonce, ciphertext, NUM_ROUNDS);
    }
}
